export const affiliations = [
  "School of Graduate Studies",
  "College of Law",
  "College of Medicine",
  "College of Accountancy",
  "College of Agriculture",
  "College of Arts and Sciences",
  "College of Business Administration",
  "College of Communication",
  "College of Informatics and Computing Studies",
  "College of Criminology",
  "College of Education",
  "College of Engineering and Technology",
  "College of Medical Technology",
  "College of Midwifery",
  "College of Music",
  "College of Nursing",
  "College of Respiratory Therapy",
  "School of International Relations",
  "Other",
];
